version: '3'

services:
  frontend:
    build: ./frontend
    image: booster_opening_front
    container_name: booster_opening_front_container
    volumes:
      - ./frontend:/app:z
      - ./frontend/dist:/usr/share/nginx/html:z # Serve built files via NGINX
    ports:
      - "8081:80" # Serve static files on port 80 inside container
    command: nginx -g "daemon off;"

  backend:
    build: ./backend
    env_file:
      - ./.env
    image: booster_opening_back
    container_name: booster_opening_back_container
    volumes:
      - ./backend:/app:z
    ports:
      - "8001:8000"
      - "5679:5678"
    command: >
      bash -c "poetry run python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres