# Generated by Django 4.1.3 on 2024-08-19 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('symbol', models.ImageField(default=None, null=True, upload_to='images/Set/symbol')),
                ('logo', models.ImageField(default=None, null=True, upload_to='images/Set/Logo')),
                ('extension_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subType', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('superType', models.CharField(max_length=30)),
                ('small_image', models.ImageField(default=None, max_length=255, null=True, upload_to='images/small/')),
                ('large_image', models.ImageField(default=None, max_length=255, null=True, upload_to='images/large/')),
                ('rarity', models.CharField(max_length=30, null=True)),
                ('number', models.IntegerField()),
                ('extension_id', models.CharField(max_length=10)),
                ('holo_type', models.CharField(choices=[('N', 'No Holo'), ('H', 'Holo')], default='N', max_length=2)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.set')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
