# Generated by Django 4.1.3 on 2022-12-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("small_image", models.URLField()),
                ("large_image", models.URLField()),
                ("rarity", models.CharField(max_length=30)),
            ],
        ),
    ]
