# Generated by Django 4.1.3 on 2023-01-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default=None, null=True, upload_to='images/boosters/')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('small_image', models.ImageField(default=None, null=True, upload_to='images/small/')),
                ('large_image', models.ImageField(default=None, null=True, upload_to='images/large/')),
                ('rarity', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
