# Generated by Django 4.1.3 on 2023-02-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_card_number_card_subtype_card_supertype_card_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="type",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
