# Generated by Django 4.1.3 on 2022-12-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_alter_card_large_image_alter_card_small_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None, null=True, upload_to="images/boosters/"
                    ),
                ),
            ],
        ),
    ]
