# Generated by Django 4.1.3 on 2023-05-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='holo_type',
            field=models.CharField(choices=[('N', 'No Holo'), ('H', 'Holo')], default='N', max_length=2),
        ),
    ]
