# Generated by Django 4.1.3 on 2022-12-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_booster"),
    ]

    operations = [
        migrations.AddField(
            model_name="booster",
            name="name",
            field=models.CharField(default="test", max_length=50),
            preserve_default=False,
        ),
    ]
