# Generated by Django 4.1.3 on 2023-02-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_subtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='large_image',
            new_name='largeImage',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='small_image',
            new_name='smallImage',
        ),
    ]
