# Generated by Django 4.1.3 on 2023-04-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_rename_large_image_card_largeimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='largeImage',
            new_name='large_image',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='smallImage',
            new_name='small_image',
        ),
    ]
