# Generated by Django 4.1.3 on 2023-05-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_holo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='extension_id',
            field=models.CharField(default='CACA', max_length=10),
            preserve_default=False,
        ),
    ]
