# Generated by Django 4.1.3 on 2023-07-27 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0006_card_extension_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='extension_id',
            field=models.CharField(default='stfu', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UsersBooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.booster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
