# Generated by Django 4.1.3 on 2023-08-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_booster_extension_id_usersbooster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('symbol', models.ImageField(default=None, null=True, upload_to='images/Set/symbol')),
                ('logo', models.ImageField(default=None, null=True, upload_to='images/Set/Logo')),
                ('extension_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='usersbooster',
            name='booster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.set'),
        ),
        migrations.DeleteModel(
            name='Booster',
        ),
    ]
