# Generated by Django 4.1.3 on 2023-08-30 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0009_booster_card_user_delete_usersbooster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
