# Generated by Django 4.1.3 on 2023-12-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_rename_largeimage_card_large_image_and_more'),
        ('cards', '0010_alter_card_user'),
    ]

    operations = [
    ]
