# Generated by Django 4.1.3 on 2024-08-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_merge_20231230_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
