# Generated by Django 4.1.3 on 2023-01-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_delete_useraccount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "Users"},
        ),
    ]
